name: Update README Date

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Date
        run: |
          DATE=$(date +"%d %B %Y")
          sed -i "s/<!--LAST_UPDATED-->.*/$DATE/" README.md

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "📅 Updated date" || echo "No changes"
          git push
